### ISSUE TITLE
Didn't work for Korean characters (UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7: character maps to <undefined>)

### ISSUE THREAD

**Issue by freedom9393** [isabek/XmlToTxt#10]
Hi Isabek,

I'm really thankful for you making this repo. However it didn't work for Korean characters, or I couldn't make it? Could you please check and update it (if possible). Here is the error when I'm running the code:

```
Traceback (most recent call last):
  File "xmltotxt.py", line 33, in <module>
    main()
  File "xmltotxt.py", line 29, in main
    transformer.transform()
  File "D:\Projects\XmlToTxt\transformer.py", line 15, in transform
    classes = reader.get_classes()
  File "D:\Projects\XmlToTxt\reader.py", line 18, in get_classes
    lines = f.readlines()
  File "C:\Users\Scott\Anaconda3\envs\xmltotxt\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x81 in position 7: character maps to <undefined>
```

I'm guessing it might be an encoding issue. Thanks in advance!

**Comment by isabek** [comment]
@freedom9393. It seems like an encoding problem. 

Can you handle this issue @shashwat1998?

**Comment by shashwat1998** [comment]
> @freedom9393. It seems like an encoding problem.
> 
> Can you handle this issue @shashwat1998?

Sure! I'll fix it. @freedom9393 can you share the file you tried? It will help in testing.

**Comment by freedom9393** [comment]
@shashwat1998, here is the file. It contains Korean characters, English alpabet characters and numbers
[classes.txt](https://github.com/Isabek/XmlToTxt/files/5107746/classes.txt)

**Comment by isabek** [comment]
@freedom9393 check it again.
