### ISSUE TITLE
Support custom classes file

### ISSUE THREAD

**Issue by isabek** [isabek/XmlToTxt#12]
Need to set classes file as an optional argument. 

```
python xmltotxt.py -c custom_classes.txt -xml xml -out out
```

**Comment by isabek** [comment]
@shashwat1998 FYI.

**Comment by shashwat1998** [comment]
I'll start working on this if you didn't. Should I?

**Comment by isabek** [comment]
@shashwat1998 sure.

**Comment by isabek** [comment]
@shashwat1998 I have assigned this task to you :)
