### ISSUE TITLE
Citation for this repo

### ISSUE THREAD

**Issue by bzha5848** [isabek/XmlToTxt#16]
Hi there,

I'm looking for a citation of this repo with bitex format for my thesis. Thanks so much!!

**Comment by isabek** [comment]
Hi @bzha5848, now you can copy the citation link as shown below

![Screenshot from 2022-10-16 16-44-40](https://user-images.githubusercontent.com/2938840/196038887-1efbf528-53d5-49c7-bb29-b61ba2c0e9ee.png)

**Comment by isabek** [comment]
```
@software{Isabek_XmlToTxt_2022,
author = {Isabek, Tashiev},
doi = {10.5281/zenodo.7213207},
month = {10},
title = {{XmlToTxt}},
version = {1.0.3},
year = {2022}
}
```
