### ISSUE TITLE
ERROR:root:('Invalid numeric value "453.0395" at annotation/object[0]/bndbox/xmin',)  

### ISSUE THREAD

**Issue by hanumanraje** [isabek/XmlToTxt#2]
I GOT above error when tried to convert Hollywoodheads dataset xml file into yolo txt format. error occurs at both xmin and xmax value

![image](https://user-images.githubusercontent.com/16452970/71585047-4641be80-2b3b-11ea-89e2-bb9030a57c2d.png)

**Comment by ttducqt** [comment]
i met same problem. Do you have any ideas ?

**Comment by jigsawcoder** [comment]
I am facing same problem, please help.
