### ISSUE TITLE
output broken

### ISSUE THREAD

**Issue by skywo1f** [isabek/XmlToTxt#3]
running the base example only creates 1 file which also happens to be empty:

/dataSets/XmlToTxt$ python xmltotxt.py -xml xml -out out
Please, add 'sedan' to classes.txt file.
/dataSets/XmlToTxt$ ls out
image-0000001.txt

**Comment by isabek** [comment]
@skywo1f as it says you need to add **sedan** to **classes.txt** file.

**Comment by isabek** [comment]
@skywo1f I have updated master branch. You can pull the changes.
